global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - match:
      alertname: DeadMansSwitch
    repeat_interval: 5m
    receiver: deadmansswitch
  - match:
      alertname: KubePodCrashLooping
    repeat_interval: 5m
    receiver: email-admin
receivers:
- name: default
- name: deadmansswitch
  email_configs:
  - to: xxxx@xx.in
    from: literalice@monochromeroad.com
    smarthost: smtp.gmail.com:587
    auth_username: "xxx"
    auth_identity: "xxx"
    auth_password: "xxxx"
- name: email-admin
  email_configs:
  - to: xx@example.com
    from: literalice@monochromeroad.com
    smarthost: smtp.gmail.com:587
    auth_username: "xxx"
    auth_identity: "xxx"
    auth_password: "xxx"
